Repository strongloop/loopback4-example-shopping, pull requests merged in 2020-11, with the labels that each got.

#918 chore: fix auth tutorial links
  README.md
Labels: community-contribution, docs

#929 feat: allow using custom JWT secret token
  README.md
  packages/shopping/src/__tests__/acceptance/user-management.controller.acceptance.ts
  packages/shopping/src/application.ts
Labels: community-contribution, feature

#930 refactor: allow using any host and port on the frontend
  packages/shopping/public/config.js
Labels: community-contribution
